// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/browse/:genre?": {
    params: {
      "genre"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/browse/:genre?";
  };
  "routes/layouts/RootLayout.tsx": {
    id: "routes/layouts/RootLayout";
    page: "/" | "/browse/:genre?";
  };
  "routes/pages/Login.tsx": {
    id: "routes/pages/Login";
    page: "/";
  };
  "routes/layouts/AuthLayout.tsx": {
    id: "routes/layouts/AuthLayout";
    page: "/browse/:genre?";
  };
  "routes/pages/Browse.tsx": {
    id: "routes/pages/Browse";
    page: "/browse/:genre?";
  };
};